routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

# boss login
Route::group(['prefix' => 'boss', 'middleware' => ['purify']], function () {
	Route::get('/', 'Boss\Auth\LoginController@showLoginForm')->name('boss.login');
	Route::post('/', 'Boss\Auth\LoginController@login');
//	Route::post('logout', 'Boss\Auth\LoginController@logout')->name('boss.logout');

// Registration Routes...
//Route::get('register', 'Boss\Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Boss\Auth\RegisterController@register');

// Password Reset Routes...
	Route::get('password/reset', 'Boss\Auth\ForgotPasswordController@showLinkRequestForm')->name('boss.password.request');
	Route::post('password/email', 'Boss\Auth\ForgotPasswordController@sendResetLinkEmail')->name('boss.password.email');
	Route::get('password/reset/{token}', 'Boss\Auth\ResetPasswordController@showResetForm')->name('boss.password.reset');
	Route::post('password/reset', 'Boss\Auth\ResetPasswordController@reset');
	Route::get('/home', 'Boss\IndexController')->name('boss.home');
	Route::put('ticket/{id}', 'Boss\TicketController@update')->name('boss.ticket.update');
	Route::delete('ticket/{id}','Boss\TicketController@destroy')->name('boss.ticket.destroy');
	Route::get('ticket/{id}','Boss\TicketController@show')->name('ticket.show');
	Route::get('tickets','Boss\TicketController@index')->name('all_tickets');
	Route::get('tickets/search','Boss\TicketController@search')->name('tickets.search');
	Route::get('/nicks', 'Boss\RealAdminController@nicks')->name('admins.nicks');
	Route::post('/bind-nicks', 'Boss\RealAdminController@bindNiks')->name('admins.bindNiks');
	Route::put('/deactivate/{user_id}', 'Boss\RealAdminController@deactivate')->name('admin.deactivate');
	Route::delete('admin-activity/{id}','Boss\AdminActivityController')->name('activity.delete');
	Route::group(['prefix' => 'admins'], function () {
		Route::get('/statistics', 'Boss\StatisticController@index')->name('admins.statistics');
		Route::get('/statistics-submonth/', 'Boss\StatisticController@getStatisticsSubMonth')->name('admins.statistics_subMonths');
	});
	Route::group(['prefix' => 'services', 'middleware' => ['auth:boss']], function () {
		Route::get('/', 'Boss\ServicesController@index')->name('services.index');
		Route::put('/{service}', 'Boss\ServicesController@update')->name('services.update');
		Route::delete('/{service}', 'Boss\ServicesController@destroy')->name('services.destroy');
		Route::get('create', 'Boss\ServicesController@serviceCreate')->name('services.new');
		Route::post('create', 'Boss\ServicesController@create')->name('services.create');
		Route::get('statistic', 'Boss\ServicesStatisticController@index')->name('services.statistic');
		Route::get('getstatistic', 'Boss\ServicesStatisticController@getStatistic')->name('services.getStatistic');
		Route::post('getstatistic/service={service}&interval={interval}', 'Boss\ServicesStatisticController@sendStatisticViaEmail')->name('services.sendStatistic');
	});
	Route::group(['prefix' => 'logs'], function () {
		Route::get('/', 'Boss\LogController@index')->name('logs');
		Route::get('/clear', 'Boss\LogController@truncate_log')->name('logs_truncate');
	});

});
Route::resource('/boss/admins', 'Boss\RealAdminController')->middleware('purify');
Route::resource('/boss/deadline', 'Boss\DeadlineController')->middleware('purify');
Route::resource('/boss/email-lists', 'Boss\MailableController')->middleware(['purify', 'auth:boss']);
Route::resource('/boss/emails', 'Boss\EmailController')->middleware(['purify', 'auth:boss']);
Route::get('/', function () {
	if (Auth::check()) {
		if (Auth::guard('boss')->check()) {
			return redirect(route('boss.home'));
		}
		return redirect(route('home'));
	}
	return view('auth.login');
});
Auth::routes();
Route::match(['get', 'post'], 'register', function () {
	return view('errors.403');
})->name('register');
Route::group(['middleware' => ['purify', 'auth']], function () {
	Route::get('/home', 'Admin\HomeController@index')->name('home');
	Route::get('/statistic', 'Admin\HomeController@statistic')->name('admins.statistic');
	Route::post('admin/{id}/assign-ticket/{ticket_id}', 'Admin\TicketsController@assignTicket')->name('admin.assign-ticket');
//	Route::get('admin/{id}/assign-ticket/{ticket_id}',function(){
//		return redirect(404);
//	});
});
Route::post('assign-ticket/{ticket_id}', 'ReAssignController')->name('admin.assign');
/*Route::get('testmail/service={service}&interval={interval}',function($service,$interval,Request $request){
	return new App\Mail\ServiceStatistic($service,$interval);
})->name('services.sendStatistic');*/

app/Http/Controllers/Boss/AdminActivityController.php
<?php

namespace App\Http\Controllers\Boss;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\SysadminActivity as Sact;

class AdminActivityController extends Controller
{
	public function __invoke($id)
	{
		$sact_m = new Sact();
		if ($sact_m->destroyActivity($id)) return redirect()->back()->with('msg','Delete successful');
		return redirect()->back()->withErrors(['msg'=>'Delete not successful']);
    }
}

app/Http/Controllers/Boss/DeadlineController.php
<?php

namespace App\Http\Controllers\Boss;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use App\Models\Deadline;
use Illuminate\Database\Eloquent\ModelNotFoundException as MNF;
use Illuminate\Support\Facades\Log;
use Exception;

class DeadlineController extends Controller
{
	/**
	 * @var Array
	 */
	private 	$deadlineList;

	public function __construct()
	{
		$this->middleware('auth:boss');
		$this->deadlineList = $this->getListOfDeadlines();
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('boss.pages.deadlineAll')->with([
        	'deadlines'=>Deadline::orderByDesc('deadline')->get(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('boss.pages.deadlineAdd');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        	'hour'=>'numeric|required',
	        'minutes'=>'numeric|required|max:59'
        ]);
        $hour = $request->hour ?? 0;
        $minutes = $request->minutes ?? 0;
        $msg = 'Deadline with ID %d stored';
        $error_msg = 'Deadline not stored';
        $time = $this->convert2Time($hour,$minutes);
        $deadline_id = Deadline::firstOrCreate(['deadline'=>$time]);
        if($deadline_id) return redirect(route('deadline.index'))->with('msg',sprintf($msg,$deadline_id->id));
        else return redirect()->back()->withErrors(['msg'=>$error_msg]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    	$error_msg = 'Deadline with ID %d not found';
    	try{
    	$time = explode(":",Deadline::findOrFail($id)->deadline);
    	}
    	catch(MNF $mnf){
    		Log::error(sprintf($error_msg,$id));
    		return redirect()->back()->withErrors(['msg'=>sprintf($error_msg,$id)]);
	    }
        return view('boss.pages.deadlineEdit')->with([
        	'hour'=>$time[0],
	        'minutes'=>$time[1],
	        'id'=>$id,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    	$request->validate([
    		'hour'=> 'numeric|required|max:850',
		    'minutes'=>'numeric|required|max:59'
	    ]);
    	$error_msg = 'Deadline with ID %d not found';
    	$msg = 'Deadline with ID %d updated';
    	$time = $this->convert2Time($request->hour,$request->minutes);
    	try {
    		Deadline::findOrFail($id)->update(['deadline'=>$time]);
    		Log::info(sprintf($msg,$id));
	    }
	    catch (MNF $mnf){
    		return redirect()->back()->withErrors(['msg'=>sprintf($error_msg,$id)]);
	    }
        return redirect(route('deadline.index'))->with('msg',sprintf($msg,$id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    	$res = Deadline::find($id)->delete();
    	$msg = 'Deadline with ID %d deleted';
    	$error_msg = 'Deadline with ID %d was not deleted';
    	if ($res) {
    		Log::info(sprintf($msg,$id));
    		return redirect(route('deadline.index'))->with('msg',sprintf($msg,$id));
	    }
	    Log::error(sprintf($error_msg,$id));
        return redirect()->back()->withErrors(['msg'=>sprintf($error_msg,$id)]);
    }

	/**
	 * Convert variables 2 Time type
	 * @param int $hour
	 * @param int $minutes
	 * @return string
	 */
    private function convert2Time(int $hour,int $minutes)  {
	    $time = Carbon::createFromFormat('H:i',sprintf('%1$02d:%2$02d', $hour, $minutes))->toTimeString();
	    return $time;
    }

	/**
	 * Convert to minutes
	 * @param $time
	 * @return int
	 */
    public function explodeTime( $time) : int {
    	try{
    		$explode_time = explode(':',$time);
    		$hour = $explode_time[0];
    		$minutes = $explode_time[1];
    		$h2min = $hour*60;
    		$exploded_time = $minutes+$h2min;
	    }
	    catch(Exception $e){
		    $exploded_time = 0;
	    }
	    return $exploded_time;
    }

	/**
	 * Getting list of deadlines from DB
	 * @return array
	 */
	public function getListOfDeadlines():array
	{
		return Deadline::orderBy('deadline')->pluck('deadline')->toArray();
	}

	/**
	 * @return \Generator
	 */
	private function convertArray2Min(){
		foreach ($this->deadlineList as $deadline){
			yield $deadline;
		}
	}

	/**
	 * Convert list with deadline 2 minutes
	 * @return array
	 */
	public function getSummaryArrMinutes(){
		$timeArr=[];
		foreach ($this->convertArray2Min() as $element){
			array_push($timeArr,$this->explodeTime($element));
		}
		return $timeArr;
	}
}

app/Http/Controllers/Boss/EmailController.php
<?php

namespace App\Http\Controllers\Boss;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{
	Email
};

class EmailController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index()
	{
		$email_m = new Email();
		return view('boss.pages.emailsShowAll')->with([
			'emails' => $email_m->getAllEmails(),
		]);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('boss.pages.emailCreate');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request)
	{
		$request->validate([
			'email'=>'required|unique:emails|max:86'
		]);
		$email_m = new Email();
		$email = $request->email;
		$stored = $email_m->createNewRecord($email);
		if ($stored) return redirect(route('emails.index'))->with('msg',sprintf('E-mail %s stored in DB with id %d',$email,$stored));
		return redirect(route('emails.index'))->withErrors(['msg'=>sprintf('%s not stored',$email)]);
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		return redirect()->back();
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id)
	{
		return redirect()->back();
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id)
	{
		$request->validate([
			'email'=>'required|max:86'
		]);
		$email_m = new Email();
		$email = $request->email;
		$updated = $email_m->updateEmail($id,$email);
		if($updated)
			return redirect(route('emails.index'))->with('msg',sprintf('e-mail with id %d updated to %s',$id,$email));
		return redirect(route('emails.index'))->withErrors(['msg'=>sprintf('E-mail with id %d doesn\'t updated',$id)]);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id)
	{
		$email_m = new Email();
		$destroyed = $email_m->destroyEmail($id);
		if($destroyed) return redirect(route('emails.index'))->with('msg',sprintf('E-mail with id %d destroyed', $id));
		return redirect(route('emails.index'))->withErrors(['msg'=>sprintf('E-mail with id %d doesn\'t destroyed',$id)]);
	}
}

app/Http/Controllers/Boss/IndexController.php
<?php

namespace App\Http\Controllers\Boss;

//use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{
	Ticket, Service, Deadline, User
};
use Carbon\Carbon;
use App\Http\Controllers\Boss\DeadlineController as DLC;
//use Illuminate\Support\Facades\Session;
use App\Http\Libs\Statistic;


class IndexController extends Controller
{
	use Statistic;

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth:boss');//auth
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke()
	{
		$ticket_m = new Ticket();
		$deadline_m = new Deadline();
		$dlc = new DLC();
		$user_m = new User();
		$maxDeadline = $dlc->explodeTime($deadline_m->getMaxDeadline());
		/*$serviceTicketCounts = [];*/
		$service_all = Service::all();
		if (count($service_all)) {
			/*foreach ($service_all as $service) {
				$serviceTicketCounts[$service->name] = [
					'summary_tickets' => $ticket_m->getSummaryCountTickets($service->id),
					'open_tickets' => $ticket_m->getCountOpenTickets($service->id),
					'yesterday' => $ticket_m->getAllTicketsFromYesterday($service->id)->count(),
					'start_month' => $ticket_m->getAllTicketsFromMonth($service->id)->count(),
					'is_available'=>$service->is_available
				];
			}*/
			return view('boss.pages.home')->with([
					'ticketCounts' => $this->getStatisticFromServices(),
					'openTickets' => $ticket_m->getOpenTickets(),
					'newTickets' => $ticket_m->getNewTickets(),
					'Carbon'=>new Carbon(),
					'deadlineList'=>$dlc->getSummaryArrMinutes(),
					'maxDeadline'=>$maxDeadline,
					'active_admins'=>$user_m->getActiveAdmins(),
				]
			);
		} else {
			echo '<h2 style="text-align: center">Run <code>daemon.php</code> First!</h2>';
			return Null;
		}
	}


}

app/Http/Controllers/Boss/LogController.php
<?php

namespace App\Http\Controllers\Boss;

use App\Http\Controllers\Controller;
use http\Env\Request;

class LogController extends Controller
{
	private $log_file = 'tickets.log';
	private $path;

	public function __construct()
	{
		$this->middleware('auth:boss');
		$this->path = storage_path() . '/logs/' . $this->log_file;
	}

	public function index()
	{
		$logs = (file_exists($this->path)) ? file_get_contents($this->path) : 'File not found';
		return view('boss.pages.logs')->with(['logs' => $logs]);
	}

	public function truncate_log()
	{
		$f_p = fopen($this->path, 'r+t');
		ftruncate($f_p, 0);
		fseek($f_p, 0, SEEK_SET);
		fclose($f_p);
		return redirect(route('logs'))->with('msg','Logs cleaned');
	}
}

app/Http/Controllers/Boss/StatisticController.php
<?php

namespace App\Http\Controllers\Boss;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use App\Http\Libs\Statistic;

class StatisticController extends Controller
{
	use Statistic;
	public function __construct()
	{
		$this->middleware('auth:boss');
	}

	public function index()
	{
		return view('boss.pages.statistics')->with([
			'curr_month'=>0,
			'month_count'=>1,
			'statistic4AllAdmins'=>$this->recurseStatistic4AllAdmin(),
			'this_month'=>Carbon::now()->startOfMonth(),
		]);
	}

	/**
	 * Get statistic 4 all services with sub-month
	 * @param Request $request
	 * @return $this
	 */
	public function getStatisticsSubMonth(Request $request)
	{
		request()->validate([
			'month_count'=>'numeric',
		]);
		$month_count = $request->month_count;
		$currMonth = isset($request->curr_month)?1:0;
		if(!$month_count){
			return $this->index();
		}
		$statistics = [];
		foreach (range(0,$month_count) as $month){
			array_push($statistics,$this->recurseStatistic4AllAdmin($month));
		}
		return view('boss.pages.statisticsByMonth')->with([
		'statistic4AllAdminsByMonths'=>array_reverse($statistics),
		'Carbon'=>new Carbon(),
			'month_count'=>$month_count,
			'iterator'=>$month_count,
			'curr_month'=>$currMonth,
	]);
	}
}

resources/views/boss/pages/adminsShowAll.blade.php
@extends('boss.layout')
@section('title','Все админы')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-3">
<div class="card">
<h5 class="card-header">Админисистраторы</h5>
<div class="card-body">
<table class="table table-striped">
<tr class="text-center">
<th>#</th>
<th>ID</th>
<th>Имя</th>
<th>Активен</th>
<th class="text-right">Операции</th>
</tr>
<tbody>@php $i=0;@endphp
@foreach($admins as $admin)
<tr>
<td>{{++$i}}</td>
<td>{{$admin->id}}</td>
<td>{{$admin->name}}</td>
<td class="text-center">
@if($admin->active)
<form action="{{route('admin.deactivate',$admin->id)}}" method="post">
<input type="checkbox" name="deactivate" class="submit" checked
title="deactivate">
@csrf
@method('PUT')
</form>
@else
<i class="fas fa-minus"></i>
@endif
</td>
<td class="text-right">
<form action="{{route('admins.destroy',$admin->id)}}" method="post">
@method('DELETE')
@csrf
<button type="submit" class="btn btn-dark"
onclick="return confirm('Ви впевнені?')"><i
class="fas fa-eraser"></i>
</button>
<button data-name="{{$admin->name}}" class="rename-admin btn btn-info">
<i class="fas fa-pencil-alt"></i>
</button>
</form>
</td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
@push('js-scripts')
<script type="text/javascript" src="{{asset('js/submitOnCheckbox.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/adminRename.min.js')}}"></script>
@endpush
@endsection

resources/views/boss/pages/deadlineAdd.blade.php
@extends('boss.layout')
@section('title','Добавить deadline')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-8 mb-md-2 mb-lg-3 mx-auto">
<div class="card">
<h5 class="card-header">Временной интервал</h5>
<div class="card-body">
<form action="{{route('deadline.store')}}" method="post">
@csrf
<div class="input-group">
<div class="input-group-prepend">
<span class="input-group-text">Часы, Минуты</span>
</div>
<input type="number" aria-label="hour" class="form-control"
value="0" name="hour" min="0" max="23">
<input type="number" aria-label="minutes" class="form-control"
value="0" name="minutes" min="0" max="59">
<button type="submit" class="store-service btn btn-info">
<i class="fas fa-save"></i>
</button>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/boss/pages/deadlineAll.blade.php
@extends('boss.layout')
@section('title','Добавить deadline')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-8 mb-md-2 mb-lg-3 mx-auto">
<div class="card">
<h5 class="card-header">Временные интервалы</h5>
<div class="card-body">
<table class="table table-striped">
<thead>
<tr>
<th>ID</th>
<th>Интервал</th>
<th>Операции</th>
</tr>
</thead>
<tbody>
@foreach($deadlines as $deadline)
<tr class="text-right">
<td>{{$deadline->id}}</td>
<td>{{$deadline->deadline}}</td>
<td>
<form action="{{route('deadline.destroy',$deadline->id)}}" method="post">
@method('DELETE')
@csrf
<a href="{{route('deadline.edit',$deadline->id)}}" class="btn btn-info"><i
class="fas fa-pencil-alt"></i></a>
<button type="submit" class="btn btn-dark"
onclick="return confirm('Ви впевнені?')"><i
class="fas fa-eraser"></i>
</button>
</form>
</td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/boss/pages/emailCreate.blade.php
@extends('boss.layout')
@section('title','E-mail создать')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-3">
<div class="card">
<h5 class="card-header">Почтовый ящик</h5>
<div class="card-body">
<form action="{{route('emails.store')}}" method="post">
@csrf
<div class="input-group w-50 m-auto">
<input type="email" aria-label="email" class="form-control"
value="{{old('email')}}" name="email">
<button type="submit" class="store-service btn btn-info">
<i class="fas fa-save"></i>
</button>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/boss/pages/home.blade.php
@extends('boss.layout')
@section('title','Boss Home')
@section('main_content')
	<div class="container">
		<div class="row">
			<div class="col-md-12 mb-md-2 mb-lg-3">
				@include('boss.parts.client_statistics')
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 mb-md-2 mb-lg-3">
				@include('boss.parts.new_tickets')
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 mb-md-2 mb-lg-3">
				@include('parts.all_tickets',['deadline_cb'=>1])
			</div>
		</div>
	</div>
@endsection

resources/views/boss/pages/mailingListsEdit.blade.php
@extends('boss.layout')
@section('title','Список рассылки')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-3">
<div class="card">
<h5 class="card-header">Редактировать список рассылки</h5>
<div class="card-body">
<form action="{{route('email-lists.update',['id'=>$mailable_id])}}" class="justify-content-center form-inline" method="post">
@csrf
@method('PUT')
<div class="form-group">
@include('boss.parts.servicesList')
@include('boss.parts.intervalsList')
@include('boss.parts.emailList')
<button type="submit" class="btn btn-primary">Сохранить</button>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/boss/pages/serviceCreate.blade.php
@extends('boss.layout')
@section('title','Клиенты')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-3">
<div class="card">
<h5 class="card-header">Клиенты (тикетницы)</h5>
<div class="card-body">
<form action="{{route('services.create')}}" method="post">
@csrf
<div class="input-group">
<div class="input-group-prepend">
<span class="input-group-text">Клиент, сложность</span>
</div>
<input type="text" aria-label="name" class="form-control"
value="{{old('name')}}" name="name">
<input type="number" aria-label="compl" class="form-control"
value="@php echo old('compl')??1.0; @endphp" step=".1" name="compl" max="9.9" min="0">
<button type="submit" class="store-service btn btn-info">
<i class="fas fa-save"></i>
</button>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/boss/pages/serviceStatistic.blade.php
@extends('boss.layout')
@section('title','Статистика по клиенту')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-3">
<div class="card">
<h5 class="card-header">Фильтр</h5>
<div class="card-body">
<form action="{{route('services.getStatistic')}}"
class="justify-content-center form-inline">
<div class="form-group">
@include('boss.parts.servicesList')
@include('boss.parts.intervalsList')
<button type="submit" class="btn btn-primary">Получить</button>
</div>
</form>
</div>
</div>
</div>
</div>
@isset($statistics)
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-3">
<div class="card">
<h5 class="card-header">Отправить email</h5>
<div class="card-body">
<form method="post" class="form-inline justify-content-center"
action="{{route('services.sendStatistic',['service_id'=>$service_id,'interval'=>$interval])}}">
@csrf()
<button class="btn btn-primary">Отправить на e-mail</button>
</form>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-3">
<div class="card">
<h5 class="card-header">Результат</h5>
<div class="card-body">
@include('boss.parts.service_statistic_by_interval')
</div>
</div>
</div>
</div>
@endisset
</div>
@endsection

resources/views/boss/pages/statistics.blade.php
@extends('boss.layout')
@section('title','Статистика')
@section('main_content')
<div class="container">
<div class="row">
<div class="col-md-12 mb-md-2 mb-lg-5">
@include('parts.rates')
</div>
<div class="col-md-8 mx-auto">
@include('boss.parts.rateMonthForm')
</div>
</div>
</div>
@endsection
@push('js-scripts')
<script type="text/javascript" src="{{asset('js/slide-statistic.min.js')}}"></script>
@endpush