routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

# boss login
Route::group(['prefix' => 'boss', 'middleware' => ['purify']], function () {
	Route::get('/', 'Boss\Auth\LoginController@showLoginForm')->name('boss.login');
	Route::post('/', 'Boss\Auth\LoginController@login');
//	Route::post('logout', 'Boss\Auth\LoginController@logout')->name('boss.logout');

// Registration Routes...
//Route::get('register', 'Boss\Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Boss\Auth\RegisterController@register');

// Password Reset Routes...
	Route::get('password/reset', 'Boss\Auth\ForgotPasswordController@showLinkRequestForm')->name('boss.password.request');
	Route::post('password/email', 'Boss\Auth\ForgotPasswordController@sendResetLinkEmail')->name('boss.password.email');
	Route::get('password/reset/{token}', 'Boss\Auth\ResetPasswordController@showResetForm')->name('boss.password.reset');
	Route::post('password/reset', 'Boss\Auth\ResetPasswordController@reset');
	Route::get('/home', 'Boss\IndexController')->name('boss.home');
	Route::put('ticket/{id}', 'Boss\TicketController@update')->name('boss.ticket.update');
	Route::delete('ticket/{id}','Boss\TicketController@destroy')->name('boss.ticket.destroy');
	Route::get('ticket/{id}','Boss\TicketController@show')->name('ticket.show');
	Route::get('tickets','Boss\TicketController@index')->name('all_tickets');
	Route::get('tickets/search','Boss\TicketController@search')->name('tickets.search');
	Route::get('/nicks', 'Boss\RealAdminController@nicks')->name('admins.nicks');
	Route::post('/bind-nicks', 'Boss\RealAdminController@bindNiks')->name('admins.bindNiks');
	Route::put('/deactivate/{user_id}', 'Boss\RealAdminController@deactivate')->name('admin.deactivate');
	Route::delete('admin-activity/{id}','Boss\AdminActivityController')->name('activity.delete');
	Route::group(['prefix' => 'admins'], function () {
		Route::get('/statistics', 'Boss\StatisticController@index')->name('admins.statistics');
		Route::get('/statistics-submonth/', 'Boss\StatisticController@getStatisticsSubMonth')->name('admins.statistics_subMonths');
	});
	Route::group(['prefix' => 'services', 'middleware' => ['auth:boss']], function () {
		Route::get('/', 'Boss\ServicesController@index')->name('services.index');
		Route::put('/{service}', 'Boss\ServicesController@update')->name('services.update');
		Route::delete('/{service}', 'Boss\ServicesController@destroy')->name('services.destroy');
		Route::get('create', 'Boss\ServicesController@serviceCreate')->name('services.new');
		Route::post('create', 'Boss\ServicesController@create')->name('services.create');
		Route::get('statistic', 'Boss\ServicesStatisticController@index')->name('services.statistic');
		Route::get('getstatistic', 'Boss\ServicesStatisticController@getStatistic')->name('services.getStatistic');
		Route::post('getstatistic/service={service}&interval={interval}', 'Boss\ServicesStatisticController@sendStatisticViaEmail')->name('services.sendStatistic');
	});
	Route::group(['prefix' => 'logs'], function () {
		Route::get('/', 'Boss\LogController@index')->name('logs');
		Route::get('/clear', 'Boss\LogController@truncate_log')->name('logs_truncate');
	});

});
Route::resource('/boss/admins', 'Boss\RealAdminController')->middleware('purify');
Route::resource('/boss/deadline', 'Boss\DeadlineController')->middleware('purify');
Route::resource('/boss/email-lists', 'Boss\MailableController')->middleware(['purify', 'auth:boss']);
Route::resource('/boss/emails', 'Boss\EmailController')->middleware(['purify', 'auth:boss']);
Route::get('/', function () {
	if (Auth::check()) {
		if (Auth::guard('boss')->check()) {
			return redirect(route('boss.home'));
		}
		return redirect(route('home'));
	}
	return view('auth.login');
});
Auth::routes();
Route::match(['get', 'post'], 'register', function () {
	return view('errors.403');
})->name('register');
Route::group(['middleware' => ['purify', 'auth']], function () {
	Route::get('/home', 'Admin\HomeController@index')->name('home');
	Route::get('/statistic', 'Admin\HomeController@statistic')->name('admins.statistic');
	Route::post('admin/{id}/assign-ticket/{ticket_id}', 'Admin\TicketsController@assignTicket')->name('admin.assign-ticket');
//	Route::get('admin/{id}/assign-ticket/{ticket_id}',function(){
//		return redirect(404);
//	});
});
Route::post('assign-ticket/{ticket_id}', 'ReAssignController')->name('admin.assign');
/*Route::get('testmail/service={service}&interval={interval}',function($service,$interval,Request $request){
	return new App\Mail\ServiceStatistic($service,$interval);
})->name('services.sendStatistic');*/

app/Models/Ticket.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\{
	Collection, Model, ModelNotFoundException
};
use Illuminate\Support\Facades\Log;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class Ticket extends Model
{
	protected $fillable = ['ticketid', 'subject', 'service_id', 'status_id', 'priority_id', 'compl', 'lastreply', 'last_replier_nik_id', 'is_closed', 'has_deadline', 'last_is_admin', 'user_assign_id',];

	/**
	 * get status
	 *
	 * get' status from Statuses
	 * @return \Illuminate\Database\Eloquent\Relations\HasOne
	 */
	public function getStatus()
	{
		return $this->hasOne(Status::class, 'id', 'status_id');
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function getService()
	{
		return $this->belongsTo(Service::class, 'service_id', 'id');
	}

	/**
	 * getting count of closed tickets
	 * @param  int $service_id
	 *
	 * @return int
	 */
	public function getCountClosedTickets(int $service_id): int
	{
		return $this::where(['is_closed' => 1, 'service_id' => $service_id])->get()->count();
	}

	/**
	 *
	 * getting count of open tickets on service
	 * @param  int $service_id
	 * @return int
	 */
	public function getCountOpenTickets(int $service_id): int
	{
		return $this::where(['is_closed' => 0, 'service_id' => $service_id])->get()->count();
	}

	/**
	 * getting summary count of tickets
	 *
	 * @param $service_id
	 * @return mixed
	 */
	public function getSummaryCountTickets(int $service_id): int
	{
		return $this::where('service_id', $service_id)->get()->count();
	}

	/**
	 * get inner id from DB
	 *
	 * if exist return onw ID else 0 as new ticket
	 *
	 * @param int $tid
	 * @param int $service_id
	 * @return int
	 */
	public function getTicketIdFromDb(int $tid, int $service_id): int
	{
		try {
			$id = $this->where([['ticketid', '=', $tid], ['service_id', '=', $service_id]])->firstOrFail()->id;
		} catch (ModelNotFoundException $mnf) {
			$id = 0;
			//Log::error("Error getating ID from DB where ticketid is $tid and service_id is $service_id");
		}
		return $id;
	}

	public function getTicketId(int $ticketid, int $service_id, array $values = [])
	{
		$ticket_m = Ticket::UpdateOrCreate(['service_id' => $service_id, 'ticketid' => $ticketid], $values);
		return $ticket_m->id;
	}

	/**
	 * get array from DB 2 compare with outer array ticketid tid
	 *
	 * @param int $service_id
	 * @return array of ticketid
	 */
	public function getTidArray(int $service_id): array
	{
		return $this->where('service_id', $service_id)->
		whereBetween('lastreply', [Carbon::now()->startOfMonth(), Carbon::now()])->
		pluck('ticketid', 'id')->toArray();
	}

	/**
	 * moving\removing tickets
	 *
	 * check in removing statuses if occur's then remove else move to closed tickets table
	 * @param array $absentIds
	 */
	public function moveRemoveTicketsDecision(array $absentIds)
	{
		# statuses when we remove from tickets
		$removeStatuses = ['error'];
		foreach ($absentIds as $absentId) {
			if (in_array($absentId['status'], $removeStatuses))
				$this->removeTicket(
					array(
						$absentId['service_id'] => $absentId['absentId']
					)
				);
			else $this->moveTicket(
				array(
					$absentId['service_id'] => $absentId['absentId']
				)
			);
		}
	}

	/**
	 * get admin nicks
	 * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
	 */
	public function getAdminNiks()
	{
		return $this->hasManyThrough(AdminNik::class, SysadminActivity::class, 'ticket_id', 'id', 'id', 'sysadmin_niks_id');
	}

	/**
	 * Remove ticket from DB (ticket table) and Log it
	 *
	 * $absentId['service_id'] => $absentId['absentId']
	 * @param array $absentTicket
	 */
	private function removeTicket(array $absentTicket): void
	{
		$service_id = key($absentTicket);
		$id = $this->getTicketIdFromDb($absentTicket[$service_id], $service_id);
		if ($id) {
			$res = $this::find($id)->delete();
			Log::warning("Ticket id $absentTicket[$service_id] (service id is $service_id) removed from DB because it has had status 4 remove. Check statuses in Ticket Model", ["result" => $res]);
		} else Log::error("Ticket id $absentTicket[$service_id] (service id is $service_id) checked as remove from DB because it has had status 4 remove but it doesn't remove, real id $id is not found");
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasOne
	 */
	public function getPriority(): object
	{
		return $this->hasOne(Priority::class, 'id', 'priority_id');
	}

	/**
	 * sign (check is_closed) when ticket is checked as Closed
	 *
	 * $absentId['service_id'] => $absentId['absentId']
	 * @param array $absentTicket
	 */
	private function moveTicket(array $absentTicket): void
	{
		$service_id = key($absentTicket);
		$msg = 'Ticket id %d (service id is %d) checked as closed", result is %s';
		$id = $this->getTicketIdFromDb($absentTicket[$service_id], $service_id);
		if ($id) {
			$res = $this::find($id)->update(['is_closed' => 1]);
			Log::info(sprintf($msg, $absentTicket[$service_id], $service_id, $res));
		} else Log::error(sprintf($msg, $absentTicket[$service_id], $service_id, $id));
	}

	/**
	 * get real admins name cross sysadminNiks if applicable
	 * @return \Illuminate\Database\Eloquent\Relations\HasManyThrough
	 */
	public function getAdmin()
	{
		return $this->hasManyThrough(User::class, AdminNik::class, 'id', 'id', 'last_replier_nik_id', 'user_id');
	}

	public function getUserAssignedTicket()
	{
		return $this->hasOne(User::class, 'id', 'user_assign_id');
	}

	/**
	 * get user id which assign ticket
	 * @param int $ticket_id
	 * @return int
	 */
	public function getUserAssignId(int $ticket_id)
	{
		return $this::find($ticket_id)->user_assign_id;
	}

	/**
	 * get open tickets
	 *
	 * if need use getAdminActivity method to take all admin's activity in open ticket
	 *
	 * @return Ticket[]|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
	 */
	public function getOpenTickets()
	{
		return $this::with(['getStatus', 'getPriority', 'getService', 'getAdmin', 'getUserAssignedTicket'])->
		where('is_closed', 0)->
		orderByDesc('has_deadline')->
		orderBy('lastreply')->
		get();
	}

	/**
	 * get new tickets
	 *
	 * they don't have admin(-s) yet
	 * @return Ticket[]|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
	 */
	public function getNewTickets()
	{
		return $this::with(['getStatus', 'getPriority', 'getService', 'getAdmin'])->
		where([['is_closed', '=', 0], ['last_replier_nik_id', '=', 0]])->
//		orderBy('last_is_admin')->
		orderBy('lastreply')->
		get();
	}

	public function getNewTickets4Admin()
	{
		return $this::with(['getStatus', 'getPriority', 'getService', 'getAdmin'])->
		where([['is_closed', '=', 0],
			['user_assign_id', '=', Null]])->
		orWhere([['last_replier_nik_id', '=', 0], ['is_closed', '=', 0]])->
		whereHas('getAdmin', function ($q) {
			$q->where('active', 0);
		})->
		orderBy('lastreply')->
		get();
	}

	/**
	 * get all tickets on service from yesterday
	 *
	 * @param int $service_id
	 * @return mixed
	 */
	public function getAllTicketsFromYesterday(int $service_id)
	{
//		return $this::where([['created_at', '>=', Carbon::now()->yesterday()], ['service_id', $service_id]])->get();
		return $this::where('service_id', $service_id)->
		whereBetween('created_at', [Carbon::now()->yesterday()->startOfDay(), Carbon::now()->yesterday()->endOfDay()])->
		get();
	}

	/**
	 * get all tickets on service from month start
	 *
	 * @param int $service_id
	 * @return mixed
	 */
	public function getAllTicketsFromMonth(int $service_id)
	{
		return $this::where([['created_at', '>=', Carbon::now()->startOfMonth()], ['service_id', $service_id]])->get();
	}

	/**
	 * get admin activity in ticket
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function getAdminsActivities()
	{
		return $this->hasMany(SysadminActivity::class, 'ticket_id');
	}

	/**
	 * get all open ticket 4 admin id
	 *
	 * 4 current admin id get from DB all his open tickets
	 * @param $user_id
	 * @return Ticket[]|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
	 */
	public function getOpenTickets4CurrAdmin(int $user_id)
	{
		return $this::with(['getStatus', 'getPriority', 'getService', 'getAdmin', 'getUserAssignedTicket'])->
		where([['is_closed', '=', 0], ['user_assign_id', '=', $user_id]])->
		/*WhereHas('getAdmin', function ($f) use ($user_id) {
			$f->where('user_id', $user_id);
		})->*/
		orderBy('lastreply')->
		get();
	}

	/**
	 * Set Null value inUser_assign_id
	 * @param int $user_id
	 * @return int count of tickets nullabled
	 */
	public function setNullUserAssignId(int $user_id)
	{
		return $this::where('user_assign_id', $user_id)->update(['user_assign_id' => Null]);
	}

	/**
	 * check ticket as closed
	 *
	 * ticket is absent in incoming array then switch to closed
	 * @param int $ticketid
	 * @param int $service_id
	 * @return mixed
	 */
	public function closeTicket(int $ticketid, int $service_id)
	{
		return $this::where(['ticketid' => $ticketid, 'service_id' => $service_id])->update(['is_closed' => 1]);
	}

	/**
	 * Save new ticket
	 *
	 * @param int $ticketid
	 * @param int $service_id
	 * @param string $subject
	 * @param int $status_id
	 * @param int $priority_id
	 * @param $lastreply
	 * @return int ticket_id
	 */
	public function storeNewTicket(int $ticketid, int $service_id, string $subject, int $status_id, int $priority_id, $lastreply): int
	{
		$ticket_m = new Ticket();
		$ticket_m->ticketid = $ticketid;
		$ticket_m->service_id = $service_id;
		$ticket_m->subject = $subject;
		$ticket_m->status_id = $status_id;
		$ticket_m->priority_id = $priority_id;
		$ticket_m->lastreply = $lastreply;
		$ticket_m->save();
		return $ticket_m->id;
	}

	/**
	 * @param int $ticket_id
	 * @param int $status_id
	 * @param int $priority_id
	 * @param string $lastreply
	 * @param int $last_is_admin
	 * @param string $subject
	 */

app/Http/Controllers/Boss/AdminActivityController.php
<?php

namespace App\Http\Controllers\Boss;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\SysadminActivity as Sact;

class AdminActivityController extends Controller
{
	public function __invoke($id)
	{
		$sact_m = new Sact();
		if ($sact_m->destroyActivity($id)) return redirect()->back()->with('msg','Delete successful');
		return redirect()->back()->withErrors(['msg'=>'Delete not successful']);
    }
}

app/Http/Controllers/Boss/IndexController.php
<?php

namespace App\Http\Controllers\Boss;

//use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{
	Ticket, Service, Deadline, User
};
use Carbon\Carbon;
use App\Http\Controllers\Boss\DeadlineController as DLC;
//use Illuminate\Support\Facades\Session;
use App\Http\Libs\Statistic;


class IndexController extends Controller
{
	use Statistic;

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('auth:boss');//auth
	}

	/**
	 * Show the application dashboard.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function __invoke()
	{
		$ticket_m = new Ticket();
		$deadline_m = new Deadline();
		$dlc = new DLC();
		$user_m = new User();
		$maxDeadline = $dlc->explodeTime($deadline_m->getMaxDeadline());
		/*$serviceTicketCounts = [];*/
		$service_all = Service::all();
		if (count($service_all)) {
			/*foreach ($service_all as $service) {
				$serviceTicketCounts[$service->name] = [
					'summary_tickets' => $ticket_m->getSummaryCountTickets($service->id),
					'open_tickets' => $ticket_m->getCountOpenTickets($service->id),
					'yesterday' => $ticket_m->getAllTicketsFromYesterday($service->id)->count(),
					'start_month' => $ticket_m->getAllTicketsFromMonth($service->id)->count(),
					'is_available'=>$service->is_available
				];
			}*/
			return view('boss.pages.home')->with([
					'ticketCounts' => $this->getStatisticFromServices(),
					'openTickets' => $ticket_m->getOpenTickets(),
					'newTickets' => $ticket_m->getNewTickets(),
					'Carbon'=>new Carbon(),
					'deadlineList'=>$dlc->getSummaryArrMinutes(),
					'maxDeadline'=>$maxDeadline,
					'active_admins'=>$user_m->getActiveAdmins(),
				]
			);
		} else {
			echo '<h2 style="text-align: center">Run <code>daemon.php</code> First!</h2>';
			return Null;
		}
	}


}

resources/views/boss/parts/client_statistics.blade.php
<div class="card">
<h5 class="card-header">Кол-во тикетов</h5>
<div class="card-body">
<table class="table table-striped">
<thead>
<tr class="text-center">
<th>Service</th>
<th>count open tickets</th>
<th>summary count of tickets</th>
<th>from yesterday</th>
<th>from month start</th>
</tr>
</thead>
<tbody>
@if(isset($ticketCounts))
@foreach($ticketCounts as $service => $value)
<tr class="text-center">
<td @if(!$value['is_available'])class="lastreply-max text-left" @else class="text-left" @endif>
<a href="{{$value['home_link']}}" target="_blank"
class="btn btn-outline-dark btn-sm">{{$service}}</a>
</td>
<td>{{$value['open_tickets']}}</td>
<td>{{$value['summary_tickets']}}</td>
<td>{{$value['yesterday']}}</td>
<td>{{$value['start_month']}}</td>
</tr>
@endforeach
@endif
</tbody>
</table>
</div>
</div>

resources/views/boss/parts/emailList.blade.php
<label for="emailSelect">Получатели</label>
<select name="emails[]" multiple class="form-control mx-2" id="emailSelect" size="5">
@foreach($emails as $email)
<option value="{{$email->id}}" @if(isset($emails_ids) and in_array($email->id,$emails_ids)) selected @endif>
{{$email->email}}
</option>
@endforeach
</select>

resources/views/boss/parts/footer.blade.php
@stack('js-scripts')
<p>boss footers</p>
<p>{{config('app.version')}}</p>
@include('parts.refresh_at')

resources/views/boss/parts/intervalsList.blade.php
<select class="custom-select ml-2 mr-2" id="interval" name="interval">
@foreach($intervals as $interval_fe)
<option value="{{$interval_fe->url_attr}}" @if(isset($interval) and $interval_fe->url_attr==$interval) selected @endif>{{$interval_fe->name}}</option>
@endforeach
</select>

resources/views/boss/parts/nav.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class="container">
<a class="navbar-brand" href="{{ route('boss.home') }}">
{{ config('app.name', 'CRM tickets') }}
</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
aria-controls="navbarSupportedContent" aria-expanded="false"
aria-label="{{ __('Toggle navigation') }}">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<!-- Left Side Of Navbar -->
<ul class="navbar-nav mr-auto">
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Администраторы
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
<a class="dropdown-item" href="{{route('admins.create')}}"><i class="far fa-save"></i> Новый</a>
<a class="dropdown-item" href="{{route('admins.nicks')}}"><i class="fas fa-link"></i>
Связать</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="{{route('admins.statistics')}}">Статистика</a>
<a class="dropdown-item" href="{{route('admins.index')}}"><i class="fas fa-list"></i> Все</a>
</div>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Клиенты
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
{{--<a class="dropdown-item disabled" href="{{route('services.new')}}"><i class="far fa-save"></i> Создать</a>--}}
<a class="dropdown-item" href="{{route('services.statistic')}}"><i
class="fas fa-chart-line"></i> Статистика</a>
<a class="dropdown-item" href="{{route('all_tickets')}}"><i class="fas fa-ticket-alt"></i>
Тикеты</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="{{route('services.index')}}"><i class="fas fa-list"></i> Все</a>
</div>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
DeadLines
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
<a class="dropdown-item" href="{{route('deadline.create')}}"><i class="far fa-save"></i> Создать</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="{{route('deadline.index')}}"><i class="fas fa-list"></i> Все</a>
</div>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
E-mails
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
<a class="dropdown-item" href="{{route('emails.create')}}"><i class="far fa-save"></i>
Добавить e-mail</a>
<a class="dropdown-item" href="{{route('email-lists.create')}}"><i
class="fas fa-building"></i> Создать список рассылки</a>
<div class="dropdown-divider"></div>
<a class="dropdown-item" href="{{route('emails.index')}}"><i class="fas fa-list"></i> Все адреса</a>
<a class="dropdown-item" href="{{route('email-lists.index')}}"><i class="fas fa-list"></i>
Списки
рассылки</a>
</div>
</li>
<li class="nav-item"><a class="nav-link" href="{{route('logs')}}">Логи</a></li>
</ul>
<!-- Right Side Of Navbar -->
<ul class="navbar-nav ml-auto">
<!-- Authentication Links -->
@guest
<li class="nav-item">
<a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
</li>
@else
<li class="nav-item dropdown">
<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
{{ Auth::user()->name }} <span class="caret"></span>
</a>
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
<a class="dropdown-item" href="{{ route('logout') }}"
onclick="event.preventDefault();document.getElementById('logout-form').submit();">
<i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
</a>
<form id="logout-form" action="{{ route('logout') }}" method="POST"
style="display: none;">
@csrf
</form>
</div>
</li>
@endguest
</ul>
</div>
</div>
</nav>

resources/views/boss/parts/new_tickets.blade.php
<div class="card">
<h5 class="card-header">Новые тикеты</h5>
<div class="card-body">
<table class="table table-striped">
<thead>
<tr class="text-center">
<th>{{__('site.waiting time')}}</th>
<th>{{__('site.assign')}}</th>
<th>{{__('site.service')}}</th>
<th>{{__('site.ticket id')}}</th>
<th>{{__('site.subject')}}</th>
<th>{{__('site.last replier')}}</th>
<th>{{__('site.last reply')}}</th>
<th>{{__('site.priority')}}</th>
<th>{{__('site.status')}}</th>
</tr>
</thead>
<tbody>
@foreach($newTickets as $newTicket)
@php
$lastreply_class = setClass4lastreply($newTicket, $deadlineList,$maxDeadline);
@endphp
<tr @isset($lastreply_class) class="{{$lastreply_class}}" @endisset>
@php
$lastReplier = $newTicket->getService['name']." client";
$waitingTime = $Carbon::createFromTimeStamp(strtotime($newTicket->lastreply))->diffForHumans();
if($newTicket->last_is_admin):
foreach($newTicket->getAdmin as $admin):
$lastReplier =$admin->name;
endforeach;
endif;
@endphp
<td>{{$waitingTime}}</td>
<td>
@if($newTicket->user_assign_id)
{{$newTicket->getUserAssignedTicket['name']}}
@else Свободен
@endif
</td>
<td>{{$newTicket->getService->name}}</td>
<td>
<a href="{{$newTicket->getService->href_link}}{{$newTicket->ticketid}}" target="_blank"
class="btn btn-info">{{$newTicket->ticketid}}</a>
</td>
<td>{{$newTicket->subject}}</td>
<td>{{$lastReplier}}</td>
<td>{{$newTicket->lastreply}}</td>
<td>{{$newTicket->getPriority->priority}}</td>
<td>{{$newTicket->getStatus->name}}</td>
</tr>
@endforeach
</tbody>
</table>
</div>
</div>

resources/views/boss/parts/ratesByMonth.blade.php
<div class="card mt-3">
<h5 class="card-header">{{__('site.rate from to',['from'=>$month,'to'=>$endMonth])}}
<a href="#" class="A4WJF float-right"><i class="far fa-plus-square d-none"></i><i
class="far fa-minus-square"></i></a></h5>
<div class="card-body">
@include('parts.rate',['statistic4AllAdmins'=>$statistic4AllAdmins])
</div>
</div>

resources/views/boss/parts/scripts.blade.php
<script src="{{ mix('js/app.js') }}"></script>